feat: add musl target support (#111)
* feat: add musl target support

Changes:
- explicitly declare deps for `bzip2` and `lzma` feature.
- add musl target support using `cc` crate.

Though I choose to link native deps with the `bzip2-sys` and `lzma-sys` crates,
note that the deps could be done with cargo's `target` selector.
Let me know if you do not want to link it by default.

/cc #80

* chore: not force install cargo-travis to save time

* fix: try to fix default target error

* fix(CI): fix cargo-travis(kcov) error

Error description(see https://travis-ci.org/rust-bio/rust-htslib/builds/424648253):

```
kcov: warning: kcov: WARNING: kcov has been built without libbfd-dev (or
kcov: binutils-dev), so the --verify option will not do anything.
Can't set personality: Operation not permitted
kcov: error: Can't start/attach to /home/travis/build/rust-bio/rust-htslib/target/debug/deps/rust_htslib-b4e39d181972c8d6
Child hasn't stopped: ff00
kcov: error: Can't start/attach to /home/travis/build/rust-bio/rust-htslib/target/debug/deps/rust_htslib-b4e39d181972c8d6
error: test failed
```

Reference: roblabla/cargo-travis#38